DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'jaktraffic') THEN
        CREATE ROLE jaktraffic LOGIN PASSWORD 'your_password_here';
    ELSE
        ALTER ROLE jaktraffic WITH LOGIN PASSWORD 'your_password_here';
    END IF;
END
$$;

SELECT 'CREATE DATABASE traffic_system OWNER jaktraffic'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'traffic_system')\gexec

\connect traffic_system

GRANT ALL PRIVILEGES ON DATABASE traffic_system TO jaktraffic;
GRANT ALL ON SCHEMA public TO jaktraffic;

CREATE TABLE IF NOT EXISTS cctv_locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    stream_url TEXT DEFAULT '',
    preview_url TEXT DEFAULT '',
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    road_type TEXT DEFAULT 'city'
);

CREATE TABLE IF NOT EXISTS current_traffic (
    id INTEGER PRIMARY KEY REFERENCES cctv_locations(id) ON DELETE CASCADE,
    name TEXT,
    stream_url TEXT DEFAULT '',
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    vehicles INTEGER DEFAULT 0,
    weather TEXT DEFAULT 'Cerah',
    status TEXT DEFAULT 'HIJAU',
    risk_score INTEGER DEFAULT 0,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS traffic_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL REFERENCES cctv_locations(id) ON DELETE CASCADE,
    vehicles INTEGER DEFAULT 0,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO cctv_locations (id, name, stream_url, preview_url, lat, lng, road_type) VALUES
    -- Jakarta
    (1,  'Bendungan Hilir',            '', '', -6.2095, 106.8190, 'city'),
    (2,  'Gelora',                     '', '', -6.2168, 106.8003, 'city'),
    (3,  'Tanjung Duren',              '', '', -6.1800, 106.7737, 'city'),
    (4,  'Tomang',                     '', '', -6.1753, 106.7972, 'city'),
    (5,  'Jati Pulo',                  '', '', -6.1848, 106.8032, 'city'),
    (6,  'Kemanggisan',                '', '', -6.1897, 106.7870, 'city'),
    (7,  'Menteng',                    '', '', -6.1965, 106.8310, 'city'),
    (8,  'Pasar Manggis',              '', '', -6.2218, 106.8411, 'city'),
    (9,  'Senayan',                    '', '', -6.2272, 106.8014, 'city'),
    (10, 'Kuningan Barat',             '', '', -6.2336, 106.8238, 'city'),
    (11, 'Cikoko',                     '', '', -6.2442, 106.8513, 'city'),
    (12, 'Cengkareng Barat',           '', '', -6.1260, 106.7235, 'city'),
    (14, 'Gambir',                     '', '', -6.1793, 106.8229, 'city'),
    (15, 'Cempaka Putih',              '', '', -6.1762, 106.8676, 'city'),
    (16, 'Rawa Sari',                  '', '', -6.1887, 106.8704, 'city'),
    (17, 'Kalideres',                  '', '', -6.1473, 106.7180, 'city'),
    (18, 'Penjaringan',                '', '', -6.1284, 106.8050, 'city'),
    (19, 'Meruya Selatan',             '', '', -6.2095, 106.7381, 'city'),
    (20, 'Ragunan',                    '', '', -6.3076, 106.8274, 'city'),
    (21, 'Lebak Bulus',                '', '', -6.3123, 106.7814, 'city'),
    (22, 'Grogol Utara',               '', '', -6.2175, 106.7818, 'city'),
    (23, 'Jatinegara',                 '', '', -6.1963, 106.9052, 'city'),
    (24, 'Kampung Melayu',             '', '', -6.2368, 106.8709, 'city'),
    (25, 'Cakung Timur',               '', '', -6.1771, 106.9485, 'city'),
    (26, 'Kelapa Gading',              '', '', -6.1519, 106.8976, 'city'),
    (27, 'Sunter Jaya',                '', '', -6.1508, 106.8794, 'city'),
    (28, 'Sunter Agung',               '', '', -6.1272, 106.8550, 'city'),
    (29, 'Tol KG-PG - Kayu Putih',    '', '', -6.1754, 106.9181, 'toll'),
    (30, 'Tol KG-PG - Pulo Gadung',   '', '', -6.1781, 106.9182, 'toll'),
    (31, 'Tol KG-PG - Rawa Terate',   '', '', -6.1828, 106.9378, 'toll'),
    (32, 'Tol KG-PG - Cakung 1',      '', '', -6.1849, 106.9465, 'toll'),
    (33, 'Tol KG-PG - Cakung 2',      '', '', -6.1857, 106.9507, 'toll'),
    (34, 'Tol KG-PG - Kelapa Gading', '', '', -6.1648, 106.9125, 'toll'),
    (35, 'Tol BCKM - Cawang',         '', '', -6.2427, 106.8972, 'toll'),
    (36, 'Tol BCKM - Duren Sawit',    '', '', -6.2492, 106.9370, 'toll'),
    (37, 'Tol BCKM - Bekasi Barat',   '', '', -6.2476, 106.9772, 'toll'),
    -- Bekasi
    (38, 'Simpang Lima Bekasi',            '', '', -6.2392, 106.9936, 'city'),
    (39, 'Jl. Ahmad Yani - Kayuringin',    '', '', -6.2363, 107.0057, 'city'),
    (40, 'Jl. Cut Meutia - KH Noer Ali',   '', '', -6.2271, 106.9991, 'city'),
    (41, 'Jl. Sudirman Bekasi',            '', '', -6.2213, 106.9974, 'city'),
    (42, 'Jl. Raya Bekasi - Sumber Arta',  '', '', -6.2146, 107.0131, 'city'),
    (43, 'Tol Bekasi Timur',               '', '', -6.2604, 107.0278, 'toll'),
    (44, 'Jl. Raya Jatiwaringin',          '', '', -6.2549, 106.9855, 'city'),
    (45, 'Harapan Indah Bekasi',           '', '', -6.2099, 107.0001, 'city'),
    (46, 'Pondok Gede',                    '', '', -6.2804, 106.9739, 'city'),
    (47, 'Jl. Raya Babelan',               '', '', -6.1874, 107.0323, 'city'),
    (48, 'Jl. Lingkar Selatan Bekasi',     '', '', -6.2888, 106.9901, 'city'),
    (49, 'Kranji - Bekasi Barat',          '', '', -6.2172, 107.0003, 'city'),
    (50, 'Jl. Ir. H. Juanda Bekasi',       '', '', -6.2303, 106.9872, 'city')
ON CONFLICT (id) DO UPDATE SET
    name        = EXCLUDED.name,
    stream_url  = EXCLUDED.stream_url,
    preview_url = EXCLUDED.preview_url,
    lat         = EXCLUDED.lat,
    lng         = EXCLUDED.lng,
    road_type   = EXCLUDED.road_type;

INSERT INTO current_traffic (id, name, stream_url, lat, lng, vehicles, weather, status, risk_score, last_update)
SELECT
    id,
    name,
    stream_url,
    lat,
    lng,
    0,
    'Cerah',
    'HIJAU',
    0,
    CURRENT_TIMESTAMP
FROM cctv_locations
ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    stream_url = EXCLUDED.stream_url,
    lat        = EXCLUDED.lat,
    lng        = EXCLUDED.lng;
